# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('list', '0002_auto_20190411_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='coverphotourl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/b/b9/No_Cover.jpg',
                                   max_length=1000),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.BookDetails'),
        ),
        migrations.AlterField(
            model_name='savedforlater',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.BookDetails'),
        ),
    ]
