# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-13 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20190413_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_and_Rating',
            fields=[
                ('username', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='User_Comment', null=True)),
                ('rating', models.IntegerField(blank=True, db_column='User_Rating', null=True)),
                ('pub_date', models.DateField(blank=True, db_column='Date_Posted', null=True)),
                ('valued', models.IntegerField(blank=True, db_column='Helpfulness', null=True)),
            ],
        ),
    ]
